definitions:
  main.Album:
    properties:
      artist:
        type: string
      id:
        type: integer
      title:
        type: string
      year:
        type: integer
    type: object
info:
  contact: {}
paths:
  /albums:
    get:
      description: Get all albums from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Album'
            type: array
      summary: Get all albums
      tags:
      - albums
swagger: "2.0"
